### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [Badsauce/HolidayAppII#1]
Nice use of ternary conditionals! It doesn't seem to be working for me though when I visit the Heroku app. Also, when I submit a blank form, I get a frightening `Internal Server Error`.

**Comment by chrisvfritz** [comment]
Ah, I see. It is working, but just shows nothing when there are no holidays. Could you update this to show a message that there are no holidays on that day when none are returned by the API? And could you populate the fields with the values of `@month`, `@year`, and `@day`, so that it's more apparent what we're showing the holidays for?

**Comment by Badsauce** [comment]
Populated the fields and added an empty message. Still getting a cryptic error if year is left empty, unsure why the ternary doesn't catch it. Not really sure where to go with "NoMethodError at /
undefined method `join' for #String:0xb6350398"

**Comment by chrisvfritz** [comment]
Ahh, that's a rack bug giving you a bad message. If you add this line to your Gemfile:

``` ruby
gem 'rack', '1.5.2'
```

Then run this from your project folder:

``` bash
bundle update
```

Then whenever you `rackup`, make sure to run instead:

``` bash
bundle exec rackup
```

_Then_ you should get more meaningful errors messages. This bug showed up just in time for our class, unfortunately. :disappointed:

**Comment by Badsauce** [comment]
Ternary was not catching because ruby evaluates and empty string to true. All bugs should be fixed now

**Comment by chrisvfritz** [comment]
Hmm, it looks like Heroku is giving an `Internal Server Error` now and it looks like I get this error when testing locally as well.

``` json
{"status":400,"error":"The year parameter is required."}
```

**Comment by Badsauce** [comment]
Totally fixed it for real this time _crosses fingers_

**Comment by chrisvfritz** [comment]
:+1: :tada: Great work!
